const ACTION_TYPES = {
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  TOGGLE_MENU_STATUS: 'TOGGLE_MENU_STATUS',
  SET_MENU_STATUS: 'SET_MENU_STATUS',
  SET_PAGE: 'SET_PAGE',
  RELOAD_PAGE: 'RELOAD_PAGE',
  SET_PRELOADER_STATUS: 'SET_PRELOADER_STATUS',
};

export default ACTION_TYPES;
